### ISSUE TITLE
Can't change which segments are selected programatically

### ISSUE THREAD

**Issue by andrewash** [tayhalla/THSegmentedControl#5]
Thanks for putting this control together! I've got it working in my project, but I can't figure out how to select certain segments programatically..

With a UISegmentedControl, I can select one segment as follows:
```
self.segmentedControl.selectedSegmentIndex = someDefaultIndex
```
I have a control with 7 segments (representing the days of the week), and by default, I want 5 of them to be enabled (representing workdays).

Is this possible with THSegmentedControl?
If not, I'm open to trying to add this support to THSegmentedControl: Any idea which file I'd need to modify to do so?

All the best,
Andrew Ash

**Comment by tayhalla** [comment]
Hi Andrew,

Thanks for the comment / issue. 

So, I did think about this going into building this control, and it didn't really work to just declare a single index to be selected since this is a multiple index selection control. So, I decided to use a less common Foundation data structure to mimic UISegmentedControl's ```selectedSegmentIndex```.

The control accepts a ```NSOrderedSet``` for declaring which indexes are selected. Here's an example of creating this set and declaring that the first and third indexes should be shown as selected, and then telling THSegmentedControl to use them:

```objc
        NSOrderedSet *selections = [[NSOrderedSet alloc] initWithArray:@[@1, @3]];
        [thControl setSelectedIndexes:selections];
```

Does that solve your issue?

**Comment by andrewash** [comment]
Yes it does, I'm glad that's supported.
Thanks for the code snippet. It works great now.

**Comment by akevern** [comment]
Thank you for sharing this, it is just what I needed for my ui.  I seem to be having trouble with setSelectedIndexes in that it doesn't seem to update my THSegmentedControl.  Should it update the display immediately?  I tried a [setNeedsDisplay] after I setSelectedIndexes and that seems to update it, but then it is in a strange state (e.g. the titles are missing from the selected segments).  Have you seen this?

Thanks,
Al Kevern
